export default {
  en: {
    productPros: 'Advantages',
    price: 'price',
    baht: 'Baht',
    minPrice: 'Minimum Price',
    maxPrice: 'Maximum Price',
    howToUse: 'How to use',
    send: 'Send',
    question: 'Question',
    title: 'Title',
    message: 'Message',
  },
  th: {
    productPros: 'ข้อดีของผลิตภัณฑ์',
    price: 'ราคา',
    baht: 'บาท',
    minPrice: 'ราคาต่ำสุด',
    maxPrice: 'ราคาสูงสุด',
    howToUse: 'วิธีการใช้',
    send: 'ส่ง',
    question: 'คำถาม',
    title: 'หัวข้อ',
    message: 'ข้อความ',
  },
}
