const AUTOCOMPLETE_SETTING = 'AUTOCOMPLETE_SETTING'
const CHANGE_DEFAULT_TAB = 'CHANGE_DEFAULT_TAB'
const QUACK_ON_REFRESH_SETTING = 'QUACK_ON_REFRESH_SETTING'
const SAVE_RECENT_SETTING = 'SAVE_RECENT_SETTING'

export {
  AUTOCOMPLETE_SETTING,
  CHANGE_DEFAULT_TAB,
  QUACK_ON_REFRESH_SETTING,
  SAVE_RECENT_SETTING
}
